### PR TITLE
Consider adding "XLIFF Sync" to the pack

### PR DESCRIPTION
**Pull request by rvanbekkum**
Dear @waldo1001,

Please consider adding [XLIFF Sync](https://github.com/rvanbekkum/vsc-xliff-sync) to the AL Extension Pack, which might be useful for other AL developers to keep XLIFF files in sync with the auto-generated .g.xlf file.

Main features of this extension comprise:
* Keep translation files in sync with a base XLIFF file
* Check for missing translations in target files and have them auto-marked as missing (can also be configured to be triggered automatically after syncing)
* Check for translations that need work, e.g., detect that placeholders exist in the source text, but are missing in the translation (can also be configured to be triggered automatically after syncing; rules can be customized)
* Search and highlight missing translations or translations that need work
* Import/Copy translations for matching sources from external XLIFF files to target XLIFF files.

Please have a look and let me know what you think and whether you think it would be a good addition to the pack.

Thank you,
Rob

### CODE REVIEW

**Comment by waldo1001** [comment]
Hi, I had a look at the extension, and it really looks clean, nice and useful.  :-).
one questiont though - is it going to change any default behaviour of VSCode for people that are not aware that it is was installed in the background?

**Comment by rvanbekkum** [comment]
The extension features are only triggered from the commands it adds.
The only thing I can think of is that it adds an option "Synchronize Translation Units" to the context menu for XLIFF files and that trans-units with missing/needs-adaptation translations are highlighted when opened in VSCode, so I think nothing really shocking which changes the behaviour of VSCode.

**Comment by waldo1001** [comment]
HI @rvanbekkum , as you might have noticed, the tool made it in ;-).

Can I ask an additional question? 
What is your translation flow?  How to you manage translations for your products in practice?

I'm trying to come with a best practices on this :-/.

**Comment by rvanbekkum** [comment]
Hi @waldo1001, yes, I noticed, thanks for accepting the PR :)

Currently our translation flow is more or less as follows:
1. For each app we have at least an en-US and nl-NL file (N.B. nl-NL is the native language for most of our developers and customers). The translations in the en-US file are the same as the source text. The translations for the nl-NL file are filled in directly by developer (in case he/she speaks Dutch).
The translation files are kept in sync. and checked for common errors using XLIFF Sync in VSCode.
The translation files are edited using a dedicated application, currently we use [POEdit](https://poedit.net/) for this.

2. All the .xlf files are pushed to the Git repository, including the .g.xlf file.
With any feature that is added via a PR to the `develop` branch, any new en-US and nl-NL translations are also included (N.B. we use [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)).

3. If the app is to be translated to languages other than en-US and nl-NL, then we provide the .g.xlf to an external translation party.
In this process we also try to ensure the resulting translations are consistent with the translations in the "Base Application".
The resulting translation files are then added from a new feature branch via a PR to the `develop` branch.

Currently doing the translation for our apps this way is sufficiently manageable for us, although there are possibly some opportunities for improvement:

* In the flow described above, translations are already added in `feature` branches.
An advantage of this is that any `develop` build of the app, will include the en-US and nl-NL translations already.
If multiple feature branches exist at the same time though, this means that some merging _might_ be needed.
This does not happen for us too often though, but if it does, it's usually not that difficult to merge the files.
I think if you are working with a lot of developers on the same app simultaneously though, you would probably find yourself running into this more often.
* You need to remember to build the app to generate a possible new version of the .g.xlf file and sync. it with the translation files before you push your changes.
This is a risk: sometimes developers forget to refresh and push the .xlf files of the last committed version of the app -> this is tricky to catch in a PR review, _without_ pulling the code and building the app yourself (although, if you'd want to review thoroughly, you probably should pull and build the code)
* If you are working with a much bigger app (e.g., the "Base Application"), you probably don't want to bother with the translations in every pull request.

Some solutions I have in mind for this are the following:
1. It might be better to move the translation of the app to a moment prior to a new release of the app.
I think for this to work, the .g.xlf file(s) should be excluded from the repository, so that this file won't be pushed.
I think this is also something you suggested during your session on the NAV Techdays.
The .xlf files for the target languages could then be updated and pushed to the repository either via (1) a PR to the `develop` branch prior to the release, or (2) pushing the translations to the `release` branch.
2. Add a task in the build pipeline for your apps, which, for each app, checks whether the translation files are in sync. (N.B. trans-unit IDs of the .g.xlf file are also present in the target .xlf files). If the .xlf files are detected to be out of sync., this task could raise either warnings or errors in the build pipeline.
3. Or, maybe a combination of 1. and 2. That is, postpone the update of the translations to a moment prior to a new release, but also have the build pipeline check whether the .xlf files are in sync. with the .g.xlf file generated when the app is build.

I am looking forward to see your thoughts on this. ;)
Could you maybe share your current translation flow as well and/or some of your current ideas for best practices on this?

**Comment by rvanbekkum** [comment]
Hi @waldo1001
I'm still interested to hear about your current translation workflow ;).
Do you have some new ideas on what might be good practices working with translations?
Interested to hear anything you'd like to share on it. :)

**Pull request merged**
